apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-version-checker-pvc
  labels:
    app: app-version-checker
  namespace: misc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
